---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: inforsuiteas
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inforsuiteas
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: vendor_maxthreads_count
        target:
          type: Value
          averageValue: 512
